### ISSUE TITLE
MidiInterface constructor should not require a serial port as input.

### ISSUE THREAD

**Issue by bjarte-johansen** [FortySevenEffects/arduino_midi_library#105]
MidiInterface constructor should not require a serial port as input.

It would be preferable to be able to declare MidiInterface as member of an object instead of having to make it a global variable which can be messy. 

the following example does not compile
```c++
class S{
midi::MidiInterface <HardwareSerial, midi::DefaultSettingsNoSysex> midi1(Serial);
};
```

It would be preferable if midiinterface stored a pointer to serial adapter

**Comment by franky47** [comment]
As for the pointer vs reference question, I'd rather use a reference to avoid null pointer checking, using all the features the language can give us.
