### ISSUE TITLE
MIDI message substitution

### ISSUE THREAD

**Issue by scaramousche** [FortySevenEffects/arduino_midi_library#108]
Hi Francois, 

(disclaimer: I'm not a developer, I'm researching this functionality for a hobby project where I'm both the end user and sort of a PM — the Arduino development will be done by a friend of mine. So I apologize if my questions are a little dumb)

I have the following needs: 
1) send MIDI data from two MIDI keyboards into an Arduino board and output a single MIDI stream
2) send Note On/Off data from the one of the keyboards to a different channel in that stream (=change status 90/80 to 92/82)
3) transpose Note On/Off data from the other keyboard an octave up (=shift every note value byte up by 12)
4) replace two extreme Pitch Bend [E0 00 00] and [E0 F7 F7] messages with two specific SysEx messages
5) replace CC-1 messages [B0 01 nn] with SysEx messages containing nn as the data byte (and a Roland checksum)

Will the callback functionality in your library help me with all of these? How difficult would it be?

**Comment by franky47** [comment]
It seems possible, as long as you can tell apart the input streams (either have separate serial MIDI ports with an Arduino with at least 2 serial ports, or set them to different channels on the same wire).

**Comment by scaramousche** [comment]
Thank you!
