### ISSUE TITLE
split midi part from arduino

### ISSUE THREAD

**Issue by nicola-lunghi** [FortySevenEffects/arduino_midi_library#120]
Hi
I looked at this library and is nice
there are any issue If I split the non arduino part in a separate library?

This could be useful for other microcontroller/processor that are not arduino
(even the atmega itself without the arduino framework)

**Comment by franky47** [comment]
Hi, actually it's already the case.

The library uses templates to avoid depending explicitly on a `Stream` subclass, which exists only on Arduino. I use the library as-is on bare-metal AVR projects where I don't use the Arduino core.

The only requirement for the serial interface is the following API:
```cpp
using byte = uint8_t;

void begin(long baudrate);
void write(byte data);
int available();
byte read();
```

Such an example can be found in [`FortySevenEffects/monosynth`](https://github.com/FortySevenEffects/monosynth/tree/master/sources/monosynth-core), where the serial interface is implemented in [`FortySevenEffects/cake`](https://github.com/FortySevenEffects/cake/blob/master/io/cake_HardwareSerial.h).
