### ISSUE TITLE
Does it work with ATtiny45?

### ISSUE THREAD

**Issue by josephernest** [FortySevenEffects/arduino_midi_library#127]
I'm using an ATtiny45, and when trying the first tutorial example code, I have this:

> error: 'Serial' was not declared in this scope

> MIDI_CREATE_INSTANCE(HardwareSerial, Serial,  MIDI);

* Does this MIDI library work with ATtiny45 with the hardware serial?
* Does this MIDI library work with ATtiny45 with the software serial? -> No, because `midi.h` + `softwareserial.h` both take more than 100% of the memory of ATtiny45

**Is there a way to make midi.h work with an ATtiny45?**

**Comment by franky47** [comment]
The ATtiny45 does not have a hardware UART (serial port), it has a Universal Serial Interface which only supports SPI and I2C, so if the software serial does not fit in ROM/RAM, the MIDI library won't be able to work on that particular device, sorry.
