### ISSUE TITLE
Will this work on non-arduino like systems?

### ISSUE THREAD

**Issue by jmeile** [FortySevenEffects/arduino_midi_library#136]
Hi

I'm just wondering if this library will work on non-arduino like systems. I would like to create a MIDI project, but on a Raspberry Pi. The only thing I have found so far is rtmidi; however, it only allows to define a callback for raw MIDI messages, so, I will have to parse the MIDI message to know if it is a NOTE ON, a CONTROL CHANGE, etc..

I would like to have something as what you use here: different callbacks for the different MIDI messages: NOTE ON, NOTE OFF, CONTROL CHANGE, etc..

The idea is to use an USB to MIDI cable.

Thanks in advanced

Best regards
Josef

**Comment by jmeile** [comment]
I changed the title and the description since the code is C++. I expressed it wrongly. I wanted to know if you can use it in other systems, ie: an Raspbery Pi or even a computer with linux and an USB to MIDI cable.

**Comment by franky47** [comment]
The library uses templates to abstract the parsing from the transport used, so as long as you provide it with an interface that conforms to Arduino's Serial, it will work.

Have a look at this repository to see how to write an adapter for another platform:
https://github.com/FortySevenEffects/mbed-midi-adapter
