### ISSUE TITLE
Send Midi thru a second Serialport on a Mega2560

### ISSUE THREAD

**Issue by Rotil66** [FortySevenEffects/arduino_midi_library#140]
Hello All,
I'm new at using an Arduino and I have the following question. (probably asked a million times)
Is there a way to set the used Serialport for Midi communication to the second serial port on a mega2560. (I like to use the standard port (0) for showing info in the Serial monitor.
I can't find anything to define the used serial port (midi lib 4.3.1)

Thanks !!

**Comment by franky47** [comment]
Something like this should do the trick:

```
MIDI_CREATE_INSTANCE(HardwareSerial, Serial2, MIDI);
```
Change `Serial2` to whichever port you want to use.

**Comment by Rotil66** [comment]
Ok Thanks !!!!

⁣BlueMail voor Android downloaden ​

Op 16 feb. 2020 11:12, om 11:12, Francois Best <notifications@github.com> schreef:
