### ISSUE TITLE
MIDI 2.0

### ISSUE THREAD

**Issue by TomFrajer** [FortySevenEffects/arduino_midi_library#141]
Do you plan to add support for new MIDI 2.0 specification? Looks like HW remains same so it can be done, but of course it will be lot of work...

**Comment by franky47** [comment]
The MIDI 2.0 specification says:
> The traditional 5 pin DIN transport from MIDI 1.0 uses a byte stream rather than packets. At the moment, there is no plan to use the Universal MIDI Packet on the 5 pin DIN transport. Unless/Until that plan changes, 5 pin DIN will only support the MIDI 1.0 Protocol. 
> ...
> USB is the first target for MIDI 2.0.

This library focuses on providing a simple interface for DIN MIDI and USB. The only way I see this happening is if MIDI 2.0 becomes retro-compatible with the hardware serial transport, and we can use this library as a base to implement 2.0 specifics in a higher layer.
