### ISSUE TITLE
Version 5.0.0 "reflects" MIDI messages over USB

### ISSUE THREAD

**Issue by SteveCooling** [FortySevenEffects/arduino_midi_library#147]
Just tried to move a synth project over to versjon 5.0.0. 

I have Arduino Leonardo (clone.. a Pro micro) connected via USB. It is supposed to take MIDI messages and convert them to CV/Gate ++ for an analog synth.

Compiling using Arduino 1.8.12 on macOS 10.15.4

Two failures occur on version 5.0.0 (confirmed not a problem on version 4.3.1)

1. NoteOn and NoteOff messages are "reflected" back via USB, but with incorrect note and velocity.
2. The NoteOn/NoteOff handler callbacks in the firmware are being fred the same bad data.

See attached .ino example and screenshot of MIDI messages passed.

```c
#include <USB-MIDI.h>

USBMIDI_CREATE_DEFAULT_INSTANCE();

unsigned long t0 = millis();


#define PIN_CV 3


// -----------------------------------------------------------------------------
//
// -----------------------------------------------------------------------------
void setup()
{
  pinMode(LED_BUILTIN, OUTPUT);

  // Listen for MIDI messages on channel 1
  MIDI.begin(1);

  MIDI.setHandleNoteOn(OnMidiNoteOn);
  MIDI.setHandleNoteOff(OnMidiNoteOff);

  pinMode(PIN_CV, OUTPUT);
}

// -----------------------------------------------------------------------------
//
// -----------------------------------------------------------------------------
void loop()
{
  // Listen to incoming notes
  MIDI.read();

}


static int noteToPWM(int note) {
  return note * 2;
}

// -----------------------------------------------------------------------------
//
// -----------------------------------------------------------------------------
static void OnMidiNoteOn(byte channel, byte note, byte velocity) {
  analogWrite(PIN_CV, noteToPWM(note));
}

// -----------------------------------------------------------------------------
//
// -----------------------------------------------------------------------------
static void OnMidiNoteOff(byte channel, byte note, byte velocity) {
  //analogWrite(PIN_CV, 0);
}
```

<img width="512" alt="Skjermbilde 2020-04-22 19 29 37" src="https://user-images.githubusercontent.com/338484/80015088-86a1bf80-84d1-11ea-84f3-07ba29c14e89.png">

**Comment by franky47** [comment]
Thanks for the report, @lathoub can you have a look at the incorrect data being passed to the callbacks ?

As for the reflection, it might be due to SoftThru being enabled by default, while this makes sense for hardware MIDI, it does not for USB and probably other transports.

**Comment by lathoub** [comment]
Hi, I tried to reproduce the issue, but can't.. I have used the updated `NoteOnOffEverySec.ino` demo.

Here is my setup: Leonardo with Sparkfun MIDI shield, the shield is connected to an M-Audio MIDI USB device.

- Using 'Pocket MIDI' I send MIDI notes and they are received correctly by the Leonardo (notes, velocity and channel match)
- The Leonardo sends notes over the M-Audio and they are received correctly in 'Pocket MIDI' (in the MIDI In Monitor)

Not sure what is happening

**Comment by lathoub** [comment]
@SteveCooling have you cloned the repo or used the IDE to download the USBMIDI library?

**Comment by lathoub** [comment]
I have issued a new release of the USB-MIDI library (v1.1.0)

**Comment by SteveCooling** [comment]
I used the Library Manager in the IDE22. apr. 2020 21:15 skrev lathoub <notifications@github.com>:
@SteveCooling have you cloned the repo or used the IDE to download the USBMIDI library?

**Comment by lathoub** [comment]
The Arduino has picked up on the new release (v1.1.0) and should be fine now (I forgot to make a Release version of USB-MIDI when 5.0.0 of the MIDI Lib came out 🙈).
@SteveCooling please test again

**Comment by SteveCooling** [comment]
Tested and works fine.
Version 1.1.0 of USB-MIDI got rid of the corrupted data.
`MIDI.turnThruOff();` removed the unexpected "reflection".
👍

**Comment by franky47** [comment]
Thanks, we might need to disable Thru for non-serial transports then.

**Comment by SteveCooling** [comment]
Yes it was very unexpected behaviour, and created a loop when I routed MIDI traffic from Ableton to it 😄

**Comment by lathoub** [comment]
How about adding a method in the Transport layer:

```
...
bool thruActivated()
{
  return true;
}
...
```

in MIDI.hpp

```
template<class Transport, class Settings, class Platform>
void MidiInterface<Transport, Settings, Platform>::begin(Channel inChannel)
{
...
    mMessage.data2   = 0;
    mMessage.length  = 0;

    mThruFilterMode = Thru::Full;
    mThruActivated  = mTransport.thruActivated();
}

```

**Comment by franky47** [comment]
Good idea, it could be a static bool member rather than a function though.

**Comment by lathoub** [comment]
Ah, good!

`static const bool thruActivated = false;
`
```
...
    mThruFilterMode = Thru::Full;
    mThruActivated  = mTransport.thruActivated;
}
```

**Comment by lathoub** [comment]
pr #148
