### ISSUE TITLE
class usbMidi::usbMidiTransport' has no member named 'thruActivated' 

### ISSUE THREAD

**Issue by deladriere** [FortySevenEffects/arduino_midi_library#149]
when I do 
```
#include <USB-MIDI.h>
USBMIDI_CREATE_DEFAULT_INSTANCE();
```

I get this error
```
MIDI.hpp:97:34: error: 'class usbMidi::usbMidiTransport' has no member named 'thruActivated'
     mThruActivated  = mTransport.thruActivated;
```
But if I edit MIDI.hpp and comment that line: it compiles ok

**Comment by lathoub** [comment]
Thanks for signalling @deladriere. Somehow the thruActivated was not picked up in the v1.1.1 release of the USB-MIDI library. I fixed it in release v1.1.2 and uploaded to GitHub (should propagate to Arduino IDE within 24hrs).

**Comment by deladriere** [comment]
Ok thanks, it's working fine

**Comment by YANG-Mingcong** [comment]
Still get the same Issue

**Comment by YANG-Mingcong** [comment]
Cause in Arduino, MIDI-USB 1.1.1 version has been set as depended library. I suggest change it to 1.1.2.
Thanks a lot.
