### ISSUE TITLE
Make midi on single Atmega328p-pu

### ISSUE THREAD

**Issue by 4dvn** [FortySevenEffects/arduino_midi_library#177]
Hello, thank you for this library to work on usnoobie, can you give me a example code of 16 midi buttons from notes 36 to 51 and 4 potentiometers?

**Comment by franky47** [comment]
You can check out Notes & Volts tutorials on YouTube:

Pots: https://www.youtube.com/watch?v=DXhxdsGREsU
Buttons: https://www.youtube.com/watch?v=U9olJK3RYXg

**Comment by 4dvn** [comment]
is single board i mean this:
![board](https://user-images.githubusercontent.com/46510477/95091922-3e115200-0751-11eb-955f-d0384fd7136d.png)
