### ISSUE TITLE
Receiving device does not receive data if powered up first

### ISSUE THREAD

**Issue by Franky47** [FortySevenEffects/arduino_midi_library#20]
SourceForge reference: https://sourceforge.net/p/arduinomidilib/bugs/13/

If I power up first the Arduino Uno and afterwards the receiving device it is not possible for the receiving device to receive any midi-data. If I first power up the receiving device or if I push the Reset Button on the Arduino Uno everything works fine. Tested this with the Jomox MBase and the Elektron Octatrack, also crosschecked this with the standard serial library (there this does not occur)

**Comment by gretel** [comment]
works fine for me.
