### ISSUE TITLE
Midi note input gets reflect on midi out

### ISSUE THREAD

**Issue by amritgenius** [FortySevenEffects/arduino_midi_library#350]
im trying to get midi note on/off on an Arduino pro micro and turn on/off leds according to note on off and pitch, its working but whatever the Arduino gets over midi in port it send also to midi out port, this is calling feedback loop or something, i have tried also arduino uno instead of pro micro, same story.

**Comment by franky47** [comment]
This is called [soft Thru](https://fortyseveneffects.github.io/arduino_midi_library/a00035.html), and you can turn it off this way (in your setup function):

```c++
void setup() {
  MIDI.begin();
  MIDI.turnThruOff();
}
```

**Comment by amritgenius** [comment]
void setup() {
 MIDI.turnThruOff();
  MIDI.begin();
}

i was using in this order and that was not working. Now with your code its working well. Thankyou so much.
