### ISSUE TITLE
Status of Teensy version?

### ISSUE THREAD

**Issue by SoundGuyAndy** [FortySevenEffects/arduino_midi_library#5]
Hey Franky,
I can't quite tell from what's posted, what's the current status of the Teensy version of the MIDI Library, with USB support? I'm trying to find an easy way to merge data between UART MIDI and USB MIDI, and it's a bit of a headache going between the standard MIDI lib and Paul's USB MIDI for the Teensy. Your version looks like it'd make life a lot easier, I just can't tell if it's in a usable state, or a raw beta, or abandoned, or...?

Thanks for any insight you can give!

-Andy

**Comment by DavidMenting** [comment]
Hi Franky,
Any updates on this? My Teensy 3.1 doesn't seem to get past MIDI.begin() using MIDI library version 4.2.

**Comment by aminnie** [comment]
Hi David, 

I have been running Frank's MIDI library version 4.2 on Teensy 3.1's for more than a year - for the most part through the serial/DIN interfaces. I attempted to move to MIDI over USB in recent weeks with some success. As long as I connect to my Roland Integra-7 via MIDI-OX on a PC, midiUSB works fine. However a direct midiUSB connect between the Teensy and Integra is not working and I reverted back to DIN. From my little reading to date this may be related to USB MIDI "class compliance" implementation differences. The standard seems to be a little loose. Would be great to get USB on the Teensy's going with the Integra-7, but standard DIN works fine.

You have tried Paul's intro to MIDI examples? https://www.pjrc.com/teensy/td_libs_MIDI.html

**Comment by DavidMenting** [comment]
I managed to get this library to work by changing midi_Defs.h as in Paul's fork of this library (commit https://github.com/FortySevenEffects/arduino_midi_library/commit/95af056cdec191dd0f6241509a47bc2ab8cb81b7).

**Comment by Franky47** [comment]
I'd be happy to merge @PaulStoffregen's commits if he sends a PR, otherwise I can replicate his changes.

**Comment by PaulStoffregen** [comment]
I too would like to see everything integrated cleanly.  At the moment I can't put much time into this... but I do want to get to it eventually.

**Comment by softegg** [comment]
I'm having some trouble with running status on aftertouch occasionally dropping note off commands resulting in stuck notes on Teensy. Reading the change log suggests that this might have been fixed in 4.1, so I'm also keen to see the Teensy version brought up to the latest version.

**Comment by softegg** [comment]
I just copied the library directory over verbatim and it worked. I had to add a "library.properties" file, but that was it. I didn't test USB MIDI, just serial MIDI.
