### ISSUE TITLE
MIDI file playback ?

### ISSUE THREAD

**Issue by natcl** [FortySevenEffects/arduino_midi_library#7]
I would love the ability to read midi file from SD that would trigger the same callbacks as the midi input, is this something planned ?

**Comment by spudwebb** [comment]
I would love to see that feature too. Any chance it will be implemented?

**Comment by franky47** [comment]
@spudwebb I now have access to boards with an SD card reader, so I can start looking into it.

The file system part will probably be out of the scope of this library, and hopefully it can be implemented as an independent feature as I'd like to keep the memory footprint minimal for people who need a simple MIDI interface.

**Comment by nevvkid** [comment]
@franky47 i don't really see a big priority here. there are some projects out there to achieve midi file playback. 
+1 for more advanced integration of MIDIUSB and your lib for DIN MIDI even if they can live side by side in one project

**Comment by franky47** [comment]
Thanks for the feedback !

**Comment by natcl** [comment]
Any examples of a library that does midi file playback cleanly ?

**Comment by aminnie** [comment]
You can try this library. I have been using and modifying it as a basis for my Teensy-based setup for several years: 

https://github.com/MajicDesigns/MD_MIDIFile

I am not 100% sure what you mean by cleanly. I use this sequencer with a Roland Integra-7 for real-time play. It works well. Now and then you may have to tune the midi file a bit to fit into the ~48k limit I have on the Teensy 3.2 setup. Once it loads and runs, it is perfectly reliable.

**Comment by natcl** [comment]
Interesting, will have a look thanks!

**Comment by franky47** [comment]
Since I'd like to keep this library solely about I/O communications, I'm going to close this issue.
If you are interested in MIDI File support and have some ideas on how to integrate another library with this one, feel free to open a PR !
