### ISSUE TITLE
How to Use this lib in my IOS objective C project.

### ISSUE THREAD

**Issue by MilTravelerIos** [FortySevenEffects/arduino_midi_library#73]
Hi,

     I am trying to develop an app with the help of arduino_midi_library. But I am not getting the start point like from where I should start. When I import all of the .h and .hpp files in my code it gives me error. 

So I want to know that how can I start with this lib in my Xcode project. Is there any need of framework or anything else then please let me know.

Thanks

**Comment by Franky47** [comment]
This is an Arduino library, which is supposed to be run on an Arduino platform only.

For MIDI development on iOS, I'd suggest looking into CoreMIDI documentation:
https://developer.apple.com/reference/coremidi

**Comment by MilTravelerIos** [comment]
Thanks.
