### ISSUE TITLE
use midi library in arduino

### ISSUE THREAD

**Issue by arpeggio1234** [FortySevenEffects/arduino_midi_library#75]
Hello Francois, i use your library, midi, alot and it is working good all the time.
Many thanks and a great compliment for that.
I made myself a great arduino arpeggiator, i will sent you a link if i have made a movie on my
youtube channel, and that code for the arduino makes use of the midi library for 
midi in and midi out. I want to ask if i have permission to sell an arduino with the code inside to someone if one would be interested in the arpeggiator board.
Thanks Dian from the Netherlands

**Comment by Franky47** [comment]
Hi Dian,

Sure ! Just send a link to this repository along with the board, so your client knows what's running in their hardware.
