### ISSUE TITLE
Custom SysEx length setting works up to 63 bytes, not more. 

### ISSUE THREAD

**Issue by Razoumihine** [FortySevenEffects/arduino_midi_library#77]
Good day  :)
Not sure the issue is due to the library. 
I'm using library V 4.3.1 on an Arduino MEGA 2560, and I'm stuck on an issue where the maximum size of a receivable SysEx message is 63bytes. 
Although all defaults setting are at 128 bytes, I'm still limited at 63. This means:
If I set the SysExMaxSize = 16 , then it limits to 16 bytes
If I set the SysExMaxSize = 58 , then it limits to 58 bytes
If I set the SysExMaxSize = 64 or beyond , then it limits to 63 bytes, whatever is the max size setting. 
Here is a post on the ARDUINO forum, including the code [https://forum.arduino.cc/index.php?topic=476508.0](url)
I've no idea how to fix this.... Maybe you could help?
Cheers, 
Lionel

**Comment by Razoumihine** [comment]
Finally solved. 
Not sure why, but, I did a small code to try to find the bug: This was a loop sending a Sysex message with higher length step by step, up to 63 bytes it worked, and more it didnt. 
I assume now it is the sent message that was limited, and not the receiving one, cause with the real MIDI instrument, the arduino finally receives longer messages. 
Is the maximum length for SysEx sending is the same setting as for SysEx receiving in the library?

**Comment by Franky47** [comment]
Sending SysEx (as well as any other message type) uses the Arduino's TX buffer, which could be 64 bytes long.

The receiving part is different, in the sense that two "buffers" are involved. The RX buffer, which buffers incoming bytes between calls of MIDI.read(), and the SysEx buffer which recomposes those bytes read from MIDI.read into a meaningful SysEx message (as long as it is within the boundaries defined in the settings).

So if you need to send large SysEx, you should implement some kind of packet splitting system to make sure your message (or split parts of it) can fit into the Arduino TX buffer.
