### ISSUE TITLE
handleNoteOff random execution when it must still handling handleNoteOn

### ISSUE THREAD

**Issue by billyjoker** [FortySevenEffects/arduino_midi_library#83]
Hi my issue is that when i send for a long time a midi on message (with velocity>0), i get randomly some handleNoteOff messages, one or two messages and then continues handling the handleNoteOn correctly. 

I've debugged it and i still have no idea why this bug is happening. My test case is one channel with an increasing velocity value. It handles right 99% of the duration track (about 60 seconds), but sometimes i get rarely this handleNoteOff messages.

**Comment by franky47** [comment]
It must be whatever you're connected to that sends this message to prevent stuck notes, there's no such code in the library that does that.
