### ISSUE TITLE
[Proposal] MIDI.begin() with no arguments should listen to all channels

### ISSUE THREAD

**Issue by neilmendoza** [FortySevenEffects/arduino_midi_library#96]
Arduino only responds on channel 1 when using MidiUSB.

**Comment by krizroring** [comment]
MIDI.begin() defaults to only listen to midi channel 1, to listen to all the channels use:  MIDI.begin(MIDI_CHANNEL_OMNI);

**Comment by neilmendoza** [comment]
OK, thanks. The opposite behaviour seems more logical to me, MIDI.begin() listens to all channels and you pass a channel number to filter.

**Comment by franky47** [comment]
After some consideration, I think listening to all channels by default is a specific use-case for some particular devices. Having a silent breaking change (all other devices suddenly receiving all channels) too seems dangerous a trade-off, so we'll keep the default to channel 1, and require an explicit opt-in to listening to all channels via `MIDI.begin(MIDI_CHANNEL_OMNI)`.
