### ISSUE TITLE
MIDI thru: no matching function for call

### ISSUE THREAD

**Issue by renoized** [FortySevenEffects/arduino_midi_library#97]
I'm trying to use MIDI thru for a project but I just can't get the sketch to mirror MIDI in to MIDI out

The code is in my project as:  MIDI.setThruFilterMode(midi::Full);

The error code I get is:
no matching function for call to 'midi::MidiInterface<HardwareSerial>::setThruFilterMode(midi::MidiFilterMode)'

And I honestly don't know what I'm doing wrong. Any help would be greatly appreciated.

Alex

**Comment by franky47** [comment]
Hi Alex,

The Thru enum has moved in v4.2, the correct way to do that now is as follows:
```cpp
MIDI.setThruFilterMode(midi::Thru::Full);
```

Somehow the old definition was kept for compatibility and marked as deprecated until version 5 where removal would be complete, but it looks like your compiler did not like the `enum __attribute__ ((deprecated)) MidiFilterMode` in [`midi_Defs:105`](https://github.com/FortySevenEffects/arduino_midi_library/blob/master/src/midi_Defs.h#L105)
